services:
  - type: web
    name: momodex
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: AUTH0_AUDIENCE
        sync: false
      - key: AUTH0_DOMAIN
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: DATABASE_AUTH_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
      - key: TURSO_DATABASE_URL
        sync: false
      - key: VITE_AUTH0_CLIENT_ID
        sync: false
      - key: VITE_AUTH0_DOMAIN
        sync: false