/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */

export async function seed(knex) {
  await knex('species').del()

  await knex('species').insert([
    // ===== BIRDS — Glass Cannon (avg atk 14, dodge 25% passive) =====
    {
      id: 'kiwi',
      name: 'Kiwi',
      type: 'bird',
      hp: 28,
      attack: 10,
      attack_name: 'Peck',
      attack_two: 18,
      attack_two_name: 'Burrow Strike',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'rare',
      status: 'native',
      description:
        'A flightless, nocturnal icon of New Zealand known for its keen sense of smell and strong burrowing legs.',
      fun_fact:
        'Kiwi are the only birds in the world with nostrils at the tip of their beak, letting them sniff out worms underground.',
      effect_type: 'dodge',
      effect_value: 25,
      effect_trigger: 'passive',
    },
    {
      id: 'tui',
      name: 'Tūī',
      type: 'bird',
      hp: 26,
      attack: 16,
      attack_name: 'Song Blast',
      attack_two: 12,
      attack_two_name: 'Wing Buffet',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'common',
      status: 'native',
      description:
        'A energetic honeyeater with distinctive white throat plumes and an exceptionally loud, complex song.',
      fun_fact:
        'Tūī have two voice boxes, letting them sing two different notes at the same time.',
      effect_type: 'dodge',
      effect_value: 25,
      effect_trigger: 'passive',
    },
    {
      id: 'kea',
      name: 'Kea',
      type: 'bird',
      hp: 28,
      attack: 12,
      attack_name: 'Sharp Peck',
      attack_two: 16,
      attack_two_name: 'Aerial Dive',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'rare',
      status: 'native',
      description:
        'The world’s only alpine parrot, famous for its sharp intelligence, curiosity, and mischievous behavior.',
      fun_fact:
        'Kea are one of the only birds known to solve multi-step puzzles just for fun, not just for food.',
      effect_type: 'dodge',
      effect_value: 25,
      effect_trigger: 'passive',
    },
    {
      id: 'kakapo',
      name: 'Kākāpō',
      type: 'bird',
      hp: 30,
      attack: 9,
      attack_name: 'Gentle Peck',
      attack_two: 19,
      attack_two_name: 'Startling Boom',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'legendary',
      status: 'native',
      description:
        'A giant, critically endangered, flightless parrot with moss-green feathers and a gentle demeanor.',
      fun_fact:
        'Kākāpō can live for up to 90 years, making them one of the longest-living birds on Earth.',
      effect_type: 'dodge',
      effect_value: 25,
      effect_trigger: 'passive',
    },
    {
      id: 'takahe',
      name: 'Takahē',
      type: 'bird',
      hp: 30,
      attack: 15,
      attack_name: 'Powerful Beak',
      attack_two: 13,
      attack_two_name: 'Territorial Charge',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'legendary',
      status: 'native',
      description:
        'A large, flightless alpine bird with vibrant blue and green plumage and a powerful red beak.',
      fun_fact:
        'Takahē were thought to be extinct for 50 years until a small population was rediscovered in 1948.',
      effect_type: 'dodge',
      effect_value: 25,
      effect_trigger: 'passive',
    },
    {
      id: 'rainbow-lorikeet',
      name: 'Rainbow Lorikeet',
      type: 'bird',
      hp: 28,
      attack: 11,
      attack_name: 'Nectar Peck',
      attack_two: 17,
      attack_two_name: 'Aggressive Screech',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'rare',
      status: 'invasive',
      description:
        'A colorful Australian parrot that competes aggressively with native honeyeaters for food and nest hollows.',
      fun_fact:
        'Rainbow lorikeets have a brush-tipped tongue specially adapted for lapping up nectar.',
      effect_type: 'dodge',
      effect_value: 25,
      effect_trigger: 'passive',
    },
    {
      id: 'piwakawaka',
      name: 'Pīwakawaka (Fantail)',
      type: 'bird',
      hp: 26,
      attack: 15,
      attack_name: 'Quick Snap',
      attack_two: 13,
      attack_two_name: 'Aerial Loop',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'common',
      status: 'native',
      description:
        'A small, energetic bird known for fanning its tail and darting acrobatically to catch flying insects.',
      fun_fact:
        'Fantails often follow humans and larger animals through the bush, snapping up insects stirred up by their footsteps.',
      effect_type: 'dodge',
      effect_value: 25,
      effect_trigger: 'passive',
    },
    {
      id: 'tauhou',
      name: 'Tauhou (Silvereye)',
      type: 'bird',
      hp: 27,
      attack: 13,
      attack_name: 'Peck',
      attack_two: 15,
      attack_two_name: 'Flock Mob',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'common',
      status: 'native',
      description:
        'A small green-backed bird with a distinctive white ring around its eyes, often seen in flocks.',
      fun_fact:
        'Silvereyes self-introduced to New Zealand from Australia in the 1850s, arriving entirely on their own.',
      effect_type: 'dodge',
      effect_value: 25,
      effect_trigger: 'passive',
    },
    {
      id: 'riroriro',
      name: 'Riroriro (Grey Warbler)',
      type: 'bird',
      hp: 26,
      attack: 16,
      attack_name: 'Sharp Trill',
      attack_two: 12,
      attack_two_name: 'Nest Raid',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'common',
      status: 'native',
      description:
        'A tiny, well-camouflaged native bird best known for its long, warbling song.',
      fun_fact:
        'It builds an unusual dome-shaped hanging nest with a side entrance, woven from grass and spiderwebs.',
      effect_type: 'dodge',
      effect_value: 25,
      effect_trigger: 'passive',
    },
    {
      id: 'pukeko',
      name: 'Pūkeko',
      type: 'bird',
      hp: 28,
      attack: 12,
      attack_name: 'Stomp',
      attack_two: 16,
      attack_two_name: 'Territorial Charge',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'common',
      status: 'native',
      description:
        'A large, brightly colored swamp bird with long red legs, commonly seen strutting across paddocks.',
      fun_fact:
        'Pūkeko often raise chicks cooperatively, with several adults helping to feed and guard the same nest.',
      effect_type: 'dodge',
      effect_value: 25,
      effect_trigger: 'passive',
    },
    {
      id: 'ruru',
      name: 'Ruru (Morepork)',
      type: 'bird',
      hp: 27,
      attack: 17,
      attack_name: 'Silent Swoop',
      attack_two: 11,
      attack_two_name: 'Talon Grip',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'common',
      status: 'native',
      description:
        'New Zealand’s only surviving native owl, named after its distinctive two-note night call.',
      fun_fact:
        'Its soft-edged feathers let it fly almost completely silently while hunting at night.',
      effect_type: 'dodge',
      effect_value: 25,
      effect_trigger: 'passive',
    },
    {
      id: 'common-myna',
      name: 'Common Myna',
      type: 'bird',
      hp: 26,
      attack: 14,
      attack_name: 'Aggressive Peck',
      attack_two: 14,
      attack_two_name: 'Mob Screech',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'common',
      status: 'invasive',
      description:
        'A bold, loud introduced bird that aggressively competes with native species for nesting sites.',
      fun_fact:
        'Common mynas often gang up to mob and drive away much larger birds from shared territory.',
      effect_type: 'dodge',
      effect_value: 25,
      effect_trigger: 'passive',
    },
    {
      id: 'australian-magpie',
      name: 'Australian Magpie',
      type: 'bird',
      hp: 28,
      attack: 18,
      attack_name: 'Dive Swoop',
      attack_two: 10,
      attack_two_name: 'Warning Call',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'common',
      status: 'invasive',
      description:
        'A large black-and-white introduced bird known for aggressively defending its nesting territory.',
      fun_fact:
        'Magpies are known to swoop people who walk too close to their nests during breeding season.',
      effect_type: 'dodge',
      effect_value: 25,
      effect_trigger: 'passive',
    },

    // ===== MAMMALS — Bruiser (avg atk 11, intimidate 15% passive) =====
    {
      id: 'possum',
      name: 'Common Brushtail Possum',
      type: 'mammal',
      hp: 38,
      attack: 9,
      attack_name: 'Claw Swipe',
      attack_two: 13,
      attack_two_name: 'Night Raid',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'common',
      status: 'invasive',
      description:
        'Introduced nocturnal pest that defoliates native trees and preys on native bird eggs.',
      fun_fact:
        'A single possum can eat around 21,000 leaves a year, stripping native trees bare over time.',
      effect_type: 'intimidate',
      effect_value: 15,
      effect_trigger: 'passive',
    },
    {
      id: 'stoat',
      name: 'Stoat',
      type: 'mammal',
      hp: 40,
      attack: 12,
      attack_name: 'Claw Rake',
      attack_two: 10,
      attack_two_name: 'Ambush Bite',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'rare',
      status: 'invasive',
      description:
        'A fierce predator introduced to control rabbits that now threatens native wildlife populations.',
      fun_fact:
        'Stoats can squeeze through gaps as small as a 2-centimetre coin, making them almost impossible to fence out.',
      effect_type: 'intimidate',
      effect_value: 15,
      effect_trigger: 'passive',
    },
    {
      id: 'rabbit',
      name: 'European Rabbit',
      type: 'mammal',
      hp: 38,
      attack: 6,
      attack_name: 'Kick',
      attack_two: 16,
      attack_two_name: 'Nibble Frenzy',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'common',
      status: 'invasive',
      description:
        'A fast-breeding herbivore that causes extensive pasture damage and soil erosion.',
      fun_fact:
        'A single pair of rabbits can multiply into hundreds of descendants within just one year.',
      effect_type: 'intimidate',
      effect_value: 15,
      effect_trigger: 'passive',
    },

    // ===== INSECTS — Skirmisher (avg atk ~5, swarm x2 on attack_two) =====
    {
      id: 'weta',
      name: 'Wētā',
      type: 'insect',
      hp: 16,
      attack: 6,
      attack_name: 'Spiny Kick',
      attack_two: 4,
      attack_two_name: 'Mandible Snap',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'common',
      status: 'native',
      description:
        'An ancient, armored flightless insect native to New Zealand, known for its formidable appearance.',
      fun_fact:
        'Some wētā can survive being frozen solid in winter, then thaw out and carry on as normal.',
      effect_type: 'swarm',
      effect_value: 2,
      effect_trigger: 'on_attack',
    },
    {
      id: 'monarch-butterfly',
      name: 'Monarch Butterfly',
      type: 'insect',
      hp: 16,
      attack: 4,
      attack_name: 'Wing Flutter',
      attack_two: 6,
      attack_two_name: 'Toxic Scales',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'common',
      status: 'native',
      description:
        'A bright orange and black butterfly commonly spotted fluttering around swan plants.',
      fun_fact:
        'Monarch butterflies taste with their feet, using sensors on their legs to identify plants.',
      effect_type: 'swarm',
      effect_value: 2,
      effect_trigger: 'on_attack',
    },
    {
      id: 'wasp-german',
      name: 'German Wasp',
      type: 'insect',
      hp: 16,
      attack: 7,
      attack_name: 'Sting',
      attack_two: 3,
      attack_two_name: 'Swarm Sting',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'common',
      status: 'invasive',
      description:
        'An aggressive pest that competes heavily with native birds and insects for honeydew.',
      fun_fact:
        'A single German wasp nest can hold over 5,000 wasps by the end of summer.',
      effect_type: 'swarm',
      effect_value: 2,
      effect_trigger: 'on_attack',
    },
    {
      id: 'argentine-ant',
      name: 'Argentine Ant',
      type: 'insect',
      hp: 16,
      attack: 3,
      attack_name: 'Bite',
      attack_two: 7,
      attack_two_name: 'Colony Swarm',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'common',
      status: 'invasive',
      description:
        'An invasive ant species that forms massive supercolonies and displaces native invertebrates.',
      fun_fact:
        'Argentine ant colonies from different areas rarely fight each other, letting them form supercolonies spanning entire regions.',
      effect_type: 'swarm',
      effect_value: 2,
      effect_trigger: 'on_attack',
    },
    {
      id: 'huhu-beetle',
      name: 'Huhu Beetle',
      type: 'insect',
      hp: 16,
      attack: 6,
      attack_name: 'Chomp',
      attack_two: 4,
      attack_two_name: 'Larvae Burst',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'common',
      status: 'native',
      description:
        'New Zealand’s largest native beetle, whose grubs feed on rotting wood in native forests.',
      fun_fact:
        'Its large, wood-boring larvae were traditionally eaten by Māori as a food source.',
      effect_type: 'swarm',
      effect_value: 2,
      effect_trigger: 'on_attack',
    },
    {
      id: 'chorus-cicada',
      name: 'Chorus Cicada',
      type: 'insect',
      hp: 15,
      attack: 4,
      attack_name: 'Buzz Sting',
      attack_two: 6,
      attack_two_name: 'Deafening Chorus',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'common',
      status: 'native',
      description:
        'A native cicada known for its loud, rhythmic buzzing song heard through summer.',
      fun_fact:
        'It spends most of its life underground as a nymph before emerging for just a few weeks as an adult.',
      effect_type: 'swarm',
      effect_value: 2,
      effect_trigger: 'on_attack',
    },
    {
      id: 'bumblebee',
      name: 'Bumblebee',
      type: 'insect',
      hp: 16,
      attack: 5,
      attack_name: 'Sting',
      attack_two: 5,
      attack_two_name: 'Pollen Storm',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'common',
      status: 'invasive',
      description:
        'A large, fuzzy introduced bee that competes with native insects for flowers.',
      fun_fact:
        'Bumblebees can vibrate their flight muscles to warm up before flying on cold mornings.',
      effect_type: 'swarm',
      effect_value: 2,
      effect_trigger: 'on_attack',
    },
    {
      id: 'springbok-mantis',
      name: 'Springbok Mantis',
      type: 'insect',
      hp: 17,
      attack: 7,
      attack_name: 'Raptor Strike',
      attack_two: 3,
      attack_two_name: 'Ambush Snap',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'common',
      status: 'invasive',
      description:
        'An introduced praying mantis that preys on native insects, including New Zealand’s native mantis.',
      fun_fact:
        'It can rotate its head almost 180 degrees to track prey without moving its body.',
      effect_type: 'swarm',
      effect_value: 2,
      effect_trigger: 'on_attack',
    },
    {
      id: 'painted-lady',
      name: 'Painted Lady Butterfly',
      type: 'insect',
      hp: 15,
      attack: 3,
      attack_name: 'Wing Flutter',
      attack_two: 7,
      attack_two_name: 'Flutter Swarm',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'common',
      status: 'native',
      description:
        'A migratory orange-and-black butterfly that reaches New Zealand under its own power.',
      fun_fact:
        'This species is found on every continent except Antarctica, one of the most widespread butterflies in the world.',
      effect_type: 'swarm',
      effect_value: 2,
      effect_trigger: 'on_attack',
    },

    // ===== PLANTS — Tank (avg atk 7, lifesteal 50% on attack_two) =====
    {
      id: 'silver-fern',
      name: 'Silver Fern',
      type: 'plant',
      hp: 58,
      attack: 5,
      attack_name: 'Frond Whip',
      attack_two: 9,
      attack_two_name: 'Silver Shine Drain',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'common',
      status: 'native',
      description:
        'An iconic tree fern recognizable by the striking silver color on the underside of its fronds.',
      fun_fact:
        'Early Māori travelers used to turn over silver fern fronds to reflect moonlight and mark trail paths at night.',
      effect_type: 'lifesteal',
      effect_value: 50,
      effect_trigger: 'on_attack',
    },
    {
      id: 'kauri',
      name: 'Kauri',
      type: 'plant',
      hp: 65,
      attack: 9,
      attack_name: 'Root Slam',
      attack_two: 5,
      attack_two_name: 'Falling Branch Drain',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'legendary',
      status: 'native',
      description:
        'A majestic, ancient forest giant that can live for over a thousand years.',
      fun_fact:
        'Some living kauri trees in New Zealand are estimated to be over 2,000 years old.',
      effect_type: 'lifesteal',
      effect_value: 50,
      effect_trigger: 'on_attack',
    },
    {
      id: 'pohutukawa',
      name: 'Pōhutukawa',
      type: 'plant',
      hp: 62,
      attack: 6,
      attack_name: 'Root Grip',
      attack_two: 8,
      attack_two_name: 'Crimson Bloom Drain',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'rare',
      status: 'native',
      description:
        'New Zealand’s Christmas tree, famous for blooming bright crimson flowers along coastal cliffs.',
      fun_fact:
        'Pōhutukawa roots can grip bare rock faces, letting the tree grow sideways out of coastal cliffs.',
      effect_type: 'lifesteal',
      effect_value: 50,
      effect_trigger: 'on_attack',
    },
    {
      id: 'gorse',
      name: 'Gorse',
      type: 'plant',
      hp: 58,
      attack: 6,
      attack_name: 'Thorn Jab',
      attack_two: 8,
      attack_two_name: 'Root Drain',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'common',
      status: 'invasive',
      description:
        'A prickly, fast-spreading shrub that overtakes farmland and native vegetation.',
      fun_fact:
        'Gorse seeds can stay dormant in soil for over 50 years before sprouting.',
      effect_type: 'lifesteal',
      effect_value: 50,
      effect_trigger: 'on_attack',
    },
    {
      id: 'old-mans-beard',
      name: "Old Man's Beard",
      type: 'plant',
      hp: 58,
      attack: 5,
      attack_name: 'Smother',
      attack_two: 9,
      attack_two_name: 'Vine Choke Drain',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'common',
      status: 'invasive',
      description:
        'A fast-growing climbing vine that smothers native forest canopies.',
      fun_fact:
        "Old Man's Beard can grow up to 30cm a week, quickly blanketing entire trees.",
      effect_type: 'lifesteal',
      effect_value: 50,
      effect_trigger: 'on_attack',
    },
    {
      id: 'cabbage-tree',
      name: 'Tī Kōuka (Cabbage Tree)',
      type: 'plant',
      hp: 58,
      attack: 6,
      attack_name: 'Frond Lash',
      attack_two: 8,
      attack_two_name: 'Root Drain',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'common',
      status: 'native',
      description:
        'A distinctive palm-like tree with a tall trunk and spiky crown, found across New Zealand.',
      fun_fact:
        'Its tough, fibrous leaves were used by Māori to weave sandals, baskets, and rope.',
      effect_type: 'lifesteal',
      effect_value: 50,
      effect_trigger: 'on_attack',
    },
    {
      id: 'harakeke',
      name: 'Harakeke (NZ Flax)',
      type: 'plant',
      hp: 60,
      attack: 5,
      attack_name: 'Leaf Slice',
      attack_two: 9,
      attack_two_name: 'Fibre Drain',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'common',
      status: 'native',
      description:
        'A tough, flax-like plant with long strap-shaped leaves, historically vital for weaving and rope.',
      fun_fact:
        'Harakeke fibre is exceptionally strong, and different varieties were bred by Māori for specific weaving purposes.',
      effect_type: 'lifesteal',
      effect_value: 50,
      effect_trigger: 'on_attack',
    },
    {
      id: 'mahoe',
      name: 'Māhoe (Whiteywood)',
      type: 'plant',
      hp: 57,
      attack: 7,
      attack_name: 'Branch Whip',
      attack_two: 7,
      attack_two_name: 'Sap Drain',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'common',
      status: 'native',
      description:
        'A fast-growing native tree with pale bark, often one of the first trees to regenerate cleared forest.',
      fun_fact:
        'Its wood is so soft and light that it was traditionally used by Māori to create fire by friction.',
      effect_type: 'lifesteal',
      effect_value: 50,
      effect_trigger: 'on_attack',
    },
    {
      id: 'pampas-grass',
      name: 'Pampas Grass',
      type: 'plant',
      hp: 58,
      attack: 8,
      attack_name: 'Blade Cut',
      attack_two: 6,
      attack_two_name: 'Root Choke Drain',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'common',
      status: 'invasive',
      description:
        'A tall, invasive grass with feathery plumes that rapidly colonizes cleared and coastal land.',
      fun_fact:
        'A single plant can produce over a million wind-dispersed seeds in one season.',
      effect_type: 'lifesteal',
      effect_value: 50,
      effect_trigger: 'on_attack',
    },
    {
      id: 'buddleia',
      name: 'Buddleia',
      type: 'plant',
      hp: 59,
      attack: 6,
      attack_name: 'Vine Lash',
      attack_two: 8,
      attack_two_name: 'Nectar Drain',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'common',
      status: 'invasive',
      description:
        'A fast-spreading invasive shrub with purple flower spikes, often found colonizing riverbanks and waste ground.',
      fun_fact:
        'A single mature plant can release up to three million tiny wind-blown seeds each year.',
      effect_type: 'lifesteal',
      effect_value: 50,
      effect_trigger: 'on_attack',
    },

    // ===== FUNGI — Attrition (avg atk 3, poison 3dmg/turn on attack_two) — all new =====
    {
      id: 'werewere-kokako',
      name: 'Werewere-kōkako',
      type: 'fungi',
      hp: 49,
      attack: 2,
      attack_name: 'Spore Puff',
      attack_two: 4,
      attack_two_name: 'Toxic Bloom',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'legendary',
      status: 'native',
      description:
        'A strikingly bright blue mushroom found in native forest leaf litter, one of the most vividly colored fungi in the world.',
      fun_fact:
        "Its brilliant blue color made it famous as the flower on New Zealand's fifty-dollar banknote.",
      effect_type: 'poison',
      effect_value: 3,
      effect_trigger: 'on_attack',
    },
    {
      id: 'basket-fungus',
      name: 'Basket Fungus',
      type: 'fungi',
      hp: 47,
      attack: 2,
      attack_name: 'Foul Odor',
      attack_two: 4,
      attack_two_name: 'Lattice Poison',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'rare',
      status: 'native',
      description:
        'A bizarre, ball-shaped lattice fungus that emerges from an egg-like sac in native forests.',
      fun_fact:
        'It releases a foul smell to attract flies, which then help spread its spores.',
      effect_type: 'poison',
      effect_value: 3,
      effect_trigger: 'on_attack',
    },
    {
      id: 'beech-strawberry',
      name: 'Beech Strawberry',
      type: 'fungi',
      hp: 45,
      attack: 1,
      attack_name: 'Sap Drain',
      attack_two: 5,
      attack_two_name: 'Parasitic Spores',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'common',
      status: 'native',
      description:
        'A round, golf ball-sized fungus that grows exclusively on native beech trees.',
      fun_fact:
        'It forms galls directly on beech branches, feeding off the living tree.',
      effect_type: 'poison',
      effect_value: 3,
      effect_trigger: 'on_attack',
    },
    {
      id: 'turkey-tail',
      name: 'Turkey Tail',
      type: 'fungi',
      hp: 45,
      attack: 2,
      attack_name: 'Spore Release',
      attack_two: 4,
      attack_two_name: 'Slow Decay',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'common',
      status: 'native',
      description:
        'A fan-shaped bracket fungus with colorful concentric rings, commonly found on dead wood.',
      fun_fact:
        'Its banded rings can display a wide range of colors depending on the wood it grows on.',
      effect_type: 'poison',
      effect_value: 3,
      effect_trigger: 'on_attack',
    },
    {
      id: 'common-puffball',
      name: 'Common Puffball',
      type: 'fungi',
      hp: 45,
      attack: 3,
      attack_name: 'Spore Burst',
      attack_two: 3,
      attack_two_name: 'Choking Cloud',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'common',
      status: 'native',
      description:
        'A round white fungus that releases a visible cloud of spores when disturbed.',
      fun_fact:
        'A mature puffball can release trillions of spores in a single burst.',
      effect_type: 'poison',
      effect_value: 3,
      effect_trigger: 'on_attack',
    },
    {
      id: 'horses-hoof-fungus',
      name: "Horse's Hoof Fungus",
      type: 'fungi',
      hp: 45,
      attack: 2,
      attack_name: 'Hard Knock',
      attack_two: 4,
      attack_two_name: 'Rot Spread',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'common',
      status: 'native',
      description:
        'A hard, hoof-shaped bracket fungus that grows on dead or dying trees.',
      fun_fact:
        'Its tough, woody shell can persist on a fallen tree for years.',
      effect_type: 'poison',
      effect_value: 3,
      effect_trigger: 'on_attack',
    },
    {
      id: 'jelly-ear-fungus',
      name: 'Jelly Ear Fungus',
      type: 'fungi',
      hp: 45,
      attack: 1,
      attack_name: 'Gel Slap',
      attack_two: 5,
      attack_two_name: 'Fungal Rot',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'common',
      status: 'native',
      description:
        'A rubbery, ear-shaped fungus that grows in clusters on dead branches.',
      fun_fact:
        'Its jelly-like texture is soft and pliable when wet, then shrinks and hardens as it dries.',
      effect_type: 'poison',
      effect_value: 3,
      effect_trigger: 'on_attack',
    },
    {
      id: 'fly-agaric',
      name: 'Fly Agaric',
      type: 'fungi',
      hp: 47,
      attack: 2,
      attack_name: 'Toxic Bite',
      attack_two: 4,
      attack_two_name: 'Hallucinogenic Spores',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'rare',
      status: 'invasive',
      description:
        'A red-and-white spotted toadstool introduced to New Zealand alongside pine plantations.',
      fun_fact:
        'Its bright red cap makes it one of the most recognizable toadstools in the world.',
      effect_type: 'poison',
      effect_value: 3,
      effect_trigger: 'on_attack',
    },
    {
      id: 'honey-fungus',
      name: 'Honey Fungus',
      type: 'fungi',
      hp: 47,
      attack: 3,
      attack_name: 'Root Invasion',
      attack_two: 3,
      attack_two_name: 'Slow Strangle',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'rare',
      status: 'invasive',
      description:
        'A destructive fungus that spreads underground and kills trees by attacking their root systems.',
      fun_fact:
        'Its underground fungal networks can spread across huge areas, quietly attacking one tree after another.',
      effect_type: 'poison',
      effect_value: 3,
      effect_trigger: 'on_attack',
    },
    {
      id: 'death-cap',
      name: 'Death Cap',
      type: 'fungi',
      hp: 49,
      attack: 2,
      attack_name: 'Silent Strike',
      attack_two: 4,
      attack_two_name: 'Lethal Toxin',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'legendary',
      status: 'invasive',
      description:
        'One of the most poisonous fungi in the world, introduced to New Zealand and often growing near oak trees.',
      fun_fact:
        'A single cap contains enough toxin to be fatal if eaten, with no antidote.',
      effect_type: 'poison',
      effect_value: 3,
      effect_trigger: 'on_attack',
    },

    // ===== HERPS (REPTILES & AMPHIBIANS) — Evasive (avg atk 6, slippery 20% passive) =====
    {
      id: 'tuatara',
      name: 'Tuatara',
      type: 'reptile',
      hp: 19,
      attack: 6,
      attack_name: 'Bite',
      attack_two: 8,
      attack_two_name: 'Ancient Snap',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'legendary',
      status: 'native',
      description:
        'A prehistoric reptile surviving from the age of the dinosaurs, featuring a unique "third eye".',
      fun_fact:
        'Tuatara can live for over 100 years and keep growing slowly their entire lives.',
      effect_type: 'slippery',
      effect_value: 20,
      effect_trigger: 'passive',
    },
    {
      id: 'jewelled-gecko',
      name: 'Jewelled Gecko',
      type: 'reptile',
      hp: 18,
      attack: 7,
      attack_name: 'Quick Bite',
      attack_two: 5,
      attack_two_name: 'Camouflage Snap',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'rare',
      status: 'native',
      description:
        'A vividly green, live-bearing gecko found in shrubland, camouflaged among leaves.',
      fun_fact:
        'Unlike most reptiles, it gives birth to live young instead of laying eggs.',
      effect_type: 'slippery',
      effect_value: 20,
      effect_trigger: 'passive',
    },
    {
      id: 'duvaucels-gecko',
      name: "Duvaucel's Gecko",
      type: 'reptile',
      hp: 19,
      attack: 8,
      attack_name: 'Powerful Bite',
      attack_two: 4,
      attack_two_name: 'Tail Whip',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'legendary',
      status: 'native',
      description:
        'New Zealand’s largest native gecko, now mostly confined to predator-free offshore islands.',
      fun_fact:
        'It can grow to be one of the largest geckos in the world, and can live for many decades.',
      effect_type: 'slippery',
      effect_value: 20,
      effect_trigger: 'passive',
    },
    {
      id: 'forest-gecko',
      name: 'Forest Gecko',
      type: 'reptile',
      hp: 17,
      attack: 6,
      attack_name: 'Snap Bite',
      attack_two: 6,
      attack_two_name: 'Bark Blend',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'common',
      status: 'native',
      description:
        'A well-camouflaged native gecko found clinging to tree bark and rock crevices in native forest.',
      fun_fact:
        'Its mottled skin pattern lets it blend almost seamlessly into lichen-covered bark.',
      effect_type: 'slippery',
      effect_value: 20,
      effect_trigger: 'passive',
    },
    {
      id: 'otago-skink',
      name: 'Otago Skink',
      type: 'reptile',
      hp: 19,
      attack: 5,
      attack_name: 'Quick Nip',
      attack_two: 7,
      attack_two_name: 'Rock Dash',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'legendary',
      status: 'native',
      description:
        'One of New Zealand’s largest and most striking skinks, found only among rock outcrops in Otago.',
      fun_fact:
        'It can live for over 20 years and often basks in groups on the same rocky outcrop for its whole life.',
      effect_type: 'slippery',
      effect_value: 20,
      effect_trigger: 'passive',
    },
    {
      id: 'ornate-skink',
      name: 'Ornate Skink',
      type: 'reptile',
      hp: 17,
      attack: 6,
      attack_name: 'Quick Bite',
      attack_two: 6,
      attack_two_name: 'Leaf Litter Dash',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'common',
      status: 'native',
      description:
        'A small, slender native skink found darting through leaf litter and low vegetation.',
      fun_fact:
        'It can shed part of its tail to escape a predator, then slowly regrow it over time.',
      effect_type: 'slippery',
      effect_value: 20,
      effect_trigger: 'passive',
    },
    {
      id: 'plague-skink',
      name: 'Plague Skink',
      type: 'reptile',
      hp: 17,
      attack: 7,
      attack_name: 'Nip',
      attack_two: 5,
      attack_two_name: 'Rapid Scatter',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'common',
      status: 'invasive',
      description:
        'A small Australian skink that has spread rapidly across New Zealand, competing with native lizards.',
      fun_fact:
        'It reproduces far faster than native skinks, letting populations expand quickly once established.',
      effect_type: 'slippery',
      effect_value: 20,
      effect_trigger: 'passive',
    },
    {
      id: 'archeys-frog',
      name: "Archey's Frog",
      type: 'amphibian',
      hp: 19,
      attack: 5,
      attack_name: 'Weak Kick',
      attack_two: 7,
      attack_two_name: 'Motionless Freeze',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'legendary',
      status: 'native',
      description:
        'One of the world’s most ancient and primitive frogs, virtually unchanged for millions of years.',
      fun_fact:
        'Unlike most frogs, it has no tadpole stage — froglets hatch directly from eggs on land.',
      effect_type: 'slippery',
      effect_value: 20,
      effect_trigger: 'passive',
    },
    {
      id: 'hochstetters-frog',
      name: "Hochstetter's Frog",
      type: 'amphibian',
      hp: 18,
      attack: 6,
      attack_name: 'Damp Hop',
      attack_two: 6,
      attack_two_name: 'Stream Vanish',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'rare',
      status: 'native',
      description:
        'A small, well-camouflaged native frog found near cool forest streams.',
      fun_fact:
        'It has no external eardrums and does not call loudly like most frogs.',
      effect_type: 'slippery',
      effect_value: 20,
      effect_trigger: 'passive',
    },
    {
      id: 'hamiltons-frog',
      name: "Hamilton's Frog",
      type: 'amphibian',
      hp: 19,
      attack: 4,
      attack_name: 'Timid Hop',
      attack_two: 8,
      attack_two_name: 'Rock Crevice Hide',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'legendary',
      status: 'native',
      description:
        'One of the rarest frogs on Earth, surviving only on a single predator-free island reserve.',
      fun_fact:
        'Its entire wild population lives on just one small rock pile on Stephens Island.',
      effect_type: 'slippery',
      effect_value: 20,
      effect_trigger: 'passive',
    },
    {
      id: 'southern-bell-frog',
      name: 'Southern Bell Frog',
      type: 'amphibian',
      hp: 17,
      attack: 7,
      attack_name: 'Croak Lunge',
      attack_two: 5,
      attack_two_name: 'Pond Dash',
      attack_miss_chance: 5,
      attack_two_miss_chance: 15,
      rarity: 'common',
      status: 'invasive',
      description:
        'A large introduced frog now common in ponds and wetlands throughout New Zealand.',
      fun_fact:
        'Its loud, distinctive croak can often be heard well before the frog itself is spotted.',
      effect_type: 'slippery',
      effect_value: 20,
      effect_trigger: 'passive',
    },
  ])
}
