/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */

export async function seed(knex) {
  await knex('species').del()

  await knex('species').insert([
    // --- Native ---
    {
      id: 'kiwi',
      name: 'Kiwi',
      type: 'bird',
      hp: 45,
      attack: 10,
      rarity: 'rare',
      status: 'native',
      description: 'A flightless, nocturnal icon of New Zealand known for its keen sense of smell and strong burrowing legs.',
    },
    {
      id: 'tui',
      name: 'Tūī',
      type: 'bird',
      hp: 30,
      attack: 14,
      rarity: 'common',
      status: 'native',
      description: 'A energetic honeyeater with distinctive white throat plumes and an exceptionally loud, complex song.',
    },
    {
      id: 'kea',
      name: 'Kea',
      type: 'bird',
      hp: 35,
      attack: 18,
      rarity: 'rare',
      status: 'native',
      description: 'The world’s only alpine parrot, famous for its sharp intelligence, curiosity, and mischievous behavior.',
    },
    {
      id: 'kakapo',
      name: 'Kākāpō',
      type: 'bird',
      hp: 50,
      attack: 8,
      rarity: 'legendary',
      status: 'native',
      description: 'A giant, critically endangered, flightless parrot with moss-green feathers and a gentle demeanor.',
    },
    {
      id: 'takahe',
      name: 'Takahē',
      type: 'bird',
      hp: 48,
      attack: 12,
      rarity: 'legendary',
      status: 'native',
      description: 'A large, flightless alpine bird with vibrant blue and green plumage and a powerful red beak.',
    },
    {
      id: 'weta',
      name: 'Wētā',
      type: 'insect',
      hp: 20,
      attack: 16,
      rarity: 'common',
      status: 'native',
      description: 'An ancient, armored flightless insect native to New Zealand, known for its formidable appearance.',
    },
    {
      id: 'monarch-butterfly',
      name: 'Monarch Butterfly',
      type: 'insect',
      hp: 10,
      attack: 4,
      rarity: 'common',
      status: 'native',
      description: 'A bright orange and black butterfly commonly spotted fluttering around swan plants.',
    },
    {
      id: 'tuatara',
      name: 'Tuatara',
      type: 'reptile',
      hp: 38,
      attack: 15,
      rarity: 'rare',
      status: 'native',
      description: 'A prehistoric reptile surviving from the age of the dinosaurs, featuring a unique "third eye".',
    },
    {
      id: 'silver-fern',
      name: 'Silver Fern',
      type: 'plant',
      hp: 25,
      attack: 2,
      rarity: 'common',
      status: 'native',
      description: 'An iconic tree fern recognizable by the striking silver color on the underside of its fronds.',
    },
    {
      id: 'kauri',
      name: 'Kauri',
      type: 'plant',
      hp: 60,
      attack: 3,
      rarity: 'legendary',
      status: 'native',
      description: 'A majestic, ancient forest giant that can live for over a thousand years.',
    },
    {
      id: 'pohutukawa',
      name: 'Pōhutukawa',
      type: 'plant',
      hp: 42,
      attack: 5,
      rarity: 'rare',
      status: 'native',
      description: 'New Zealand’s Christmas tree, famous for blooming bright crimson flowers along coastal cliffs.',
    },

    // --- Invasive ---
    {
      id: 'possum',
      name: 'Common Brushtail Possum',
      type: 'mammal',
      hp: 32,
      attack: 17,
      rarity: 'common',
      status: 'invasive',
      description: 'Introduced nocturnal pest that defoliates native trees and preys on native bird eggs.',
    },
    {
      id: 'stoat',
      name: 'Stoat',
      type: 'mammal',
      hp: 22,
      attack: 22,
      rarity: 'rare',
      status: 'invasive',
      description: 'A fierce predator introduced to control rabbits that now threatens native wildlife populations.',
    },
    {
      id: 'rainbow-trout',
      name: 'Rainbow Trout',
      type: 'fish',
      hp: 28,
      attack: 13,
      rarity: 'common',
      status: 'invasive',
      description: 'A popular freshwater sport fish that competes with native galaxiid fish species for food and habitat.',
    },
    {
      id: 'wasp-german',
      name: 'German Wasp',
      type: 'insect',
      hp: 12,
      attack: 20,
      rarity: 'common',
      status: 'invasive',
      description: 'An aggressive pest that competes heavily with native birds and insects for honeydew.',
    },
    {
      id: 'rabbit',
      name: 'European Rabbit',
      type: 'mammal',
      hp: 18,
      attack: 6,
      rarity: 'common',
      status: 'invasive',
      description: 'A fast-breeding herbivore that causes extensive pasture damage and soil erosion.',
    },
    {
      id: 'gorse',
      name: 'Gorse',
      type: 'plant',
      hp: 34,
      attack: 9,
      rarity: 'common',
      status: 'invasive',
      description: 'A prickly, fast-spreading shrub that overtakes farmland and native vegetation.',
    },
    {
      id: 'old-mans-beard',
      name: "Old Man's Beard",
      type: 'plant',
      hp: 30,
      attack: 7,
      rarity: 'common',
      status: 'invasive',
      description: 'A fast-growing climbing vine that smothers native forest canopies.',
    },
    {
      id: 'rainbow-lorikeet',
      name: 'Rainbow Lorikeet',
      type: 'bird',
      hp: 24,
      attack: 11,
      rarity: 'rare',
      status: 'invasive',
      description: 'A colorful Australian parrot that competes aggressively with native honeyeaters for food and nest hollows.',
    },
    {
      id: 'argentine-ant',
      name: 'Argentine Ant',
      type: 'insect',
      hp: 8,
      attack: 6,
      rarity: 'common',
      status: 'invasive',
      description: 'An invasive ant species that forms massive supercolonies and displaces native invertebrates.',
    },
  ])
}